import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, CreditCard, LoaderCircle, Search, X } from "lucide-react";
import { PaymentChild, PaymentHistory, PaymentStatus, fetchPaymentContext, fetchPaymentHistory, setPaymentStatus } from "@/admin/paymentApi";

const inputClass="mt-1.5 w-full rounded-[13px] border border-black/[0.08] bg-white px-3.5 py-3 text-sm text-[#171717] outline-none focus:border-[#D96A24]/45 focus:ring-4 focus:ring-[#D96A24]/[0.06]";
const labels:Record<string,string>={paid:"Оплачено",pending:"Ожидает оплаты",overdue:"Просрочено","":"Статус не указан"};
function currentMonth(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function monthLabel(value:string){if(!value)return"";const d=new Date(`${value.slice(0,7)}-01T12:00:00`);return new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(d)}
function dateLabel(value:string){if(!value)return"";const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(d).replace(".","")}

export function AdminPaymentManager(){
 const[enabled,setEnabled]=useState(false),[open,setOpen]=useState(false),[children,setChildren]=useState<PaymentChild[]>([]),[query,setQuery]=useState(""),[selectedId,setSelectedId]=useState(""),[month,setMonth]=useState(currentMonth()),[status,setStatus]=useState<PaymentStatus>("pending"),[history,setHistory]=useState<PaymentHistory[]>([]),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 useEffect(()=>{let cancelled=false,timer=0;async function detect(){try{const c=await fetchPaymentContext();if(cancelled)return;setEnabled(true);setChildren(c.children)}catch{if(!cancelled)timer=window.setTimeout(detect,1400)}}detect();return()=>{cancelled=true;if(timer)window.clearTimeout(timer)}},[]);
 const selected=useMemo(()=>children.find(c=>c.id===selectedId)||null,[children,selectedId]);
 const visible=useMemo(()=>{const v=query.trim().toLowerCase();return(v?children.filter(c=>[c.name,c.branch,c.groupName].join(" ").toLowerCase().includes(v)):children).slice(0,50)},[query,children]);
 async function refresh(){const c=await fetchPaymentContext();setChildren(c.children)}
 async function openManager(){setOpen(true);setLoading(true);setError("");try{await refresh()}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить оплату.")}finally{setLoading(false)}}
 async function choose(c:PaymentChild){setSelectedId(c.id);setStatus((c.paymentStatus as PaymentStatus)||"pending");setLoading(true);setError("");setSuccess("");try{setHistory(await fetchPaymentHistory(c.id))}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить историю.")}finally{setLoading(false)}}
 async function save(){if(!selected)return setError("Выберите ребёнка.");setSaving(true);setError("");setSuccess("");try{await setPaymentStatus(selected.id,month,status);await refresh();setHistory(await fetchPaymentHistory(selected.id));setSuccess(`Статус за ${monthLabel(month)}: ${labels[status]}.`)}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить статус.")}finally{setSaving(false)}}
 if(!enabled)return null;
 return <><button type="button" onClick={openManager} className="fixed bottom-[28.7rem] right-4 z-40 flex items-center gap-2 rounded-full bg-white px-4 py-3 text-sm font-semibold text-[#171717] shadow-[0_10px_30px_rgba(0,0,0,0.18)] ring-1 ring-black/[0.06] sm:right-6"><CreditCard size={17} className="text-[#5F6338]"/> Оплата</button>
 {open&&<div className="fixed inset-0 z-[81] flex items-end justify-center bg-black/30 backdrop-blur-[2px] sm:items-center sm:p-5" onClick={()=>!saving&&setOpen(false)}><div className="max-h-[96vh] w-full max-w-5xl overflow-y-auto rounded-t-[28px] bg-[#FAF9F5] p-5 shadow-2xl sm:rounded-[28px] sm:p-7" onClick={e=>e.stopPropagation()}>
 <div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#D96A24]">OPEN STARS ADMIN</p><h2 className="mt-1 text-2xl font-semibold">Оплата</h2><p className="mt-2 text-sm text-black/45">Только статус абонемента. Суммы в приложении не используются.</p></div><button onClick={()=>setOpen(false)} className="grid h-10 w-10 place-items-center rounded-full bg-white"><X size={20}/></button></div>
 <div className="mt-6 grid gap-5 lg:grid-cols-[0.85fr_1.15fr]">
  <section className="rounded-[24px] border border-black/[0.06] bg-white p-5"><div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-black/25"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Найти ребёнка" className="w-full rounded-[14px] bg-[#FAF9F5] py-3 pl-10 pr-3 text-sm outline-none"/></div><div className="mt-3 max-h-[420px] space-y-2 overflow-y-auto">{visible.map(c=><button key={c.id} onClick={()=>choose(c)} className={`flex w-full items-center justify-between rounded-[15px] border p-3 text-left ${c.id===selectedId?"border-[#D96A24]/30 bg-[#D96A24]/[0.05]":"border-black/[0.05]"}`}><div><p className="text-sm font-semibold">{c.name}</p><p className="mt-1 text-xs text-black/35">{c.branch} · {c.groupName}</p></div><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${c.paymentStatus==="paid"?"bg-[#5F6338]/10 text-[#4D512E]":c.paymentStatus==="overdue"?"bg-red-50 text-red-600":"bg-[#D96A24]/10 text-[#C95320]"}`}>{labels[c.paymentStatus]||labels[""]}</span></button>)}</div></section>
  <div className="space-y-5"><section className="rounded-[24px] border border-black/[0.06] bg-white p-5">{selected?<><h3 className="text-lg font-semibold">{selected.name}</h3><p className="mt-1 text-xs text-black/35">{selected.branch} · {selected.groupName}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-black/55">Месяц<input type="month" className={inputClass} value={month} onChange={e=>setMonth(e.target.value)}/></label><label className="text-xs font-semibold text-black/55">Статус<select className={inputClass} value={status} onChange={e=>setStatus(e.target.value as PaymentStatus)}><option value="paid">Оплачено</option><option value="pending">Ожидает оплаты</option><option value="overdue">Просрочено</option></select></label></div><button onClick={save} disabled={saving} className="mt-5 flex w-full items-center justify-center gap-2 rounded-[14px] bg-[#171717] px-5 py-3.5 text-sm font-semibold text-white disabled:opacity-50">{saving?<LoaderCircle className="animate-spin" size={17}/>:<CreditCard size={17}/>}Сохранить статус</button></>:<div className="grid min-h-[220px] place-items-center text-center text-sm text-black/40">Выберите ребёнка слева.</div>}</section>
  {error&&<div className="rounded-[15px] border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}{success&&<div className="flex gap-2 rounded-[15px] bg-[#5F6338]/[0.07] px-4 py-3 text-sm text-[#4D512E]"><CheckCircle2 size={17}/>{success}</div>}
  <section className="rounded-[24px] border border-black/[0.06] bg-white p-5"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-black/35">История</p>{loading?<div className="grid min-h-[100px] place-items-center"><LoaderCircle className="animate-spin text-black/20"/></div>:history.length===0?<p className="mt-4 text-sm text-black/40">Изменений пока нет.</p>:<div className="mt-3 divide-y divide-black/[0.06]">{history.map(h=><div key={h.id} className="py-3"><div className="flex items-center gap-2">{h.newStatus==="paid"?<CheckCircle2 size={16} className="text-[#5F6338]"/>:<Clock3 size={16} className={h.newStatus==="overdue"?"text-red-500":"text-[#D96A24]"}/>}<p className="text-sm font-semibold">{monthLabel(h.month)} · {labels[h.newStatus]}</p></div><p className="mt-1 pl-6 text-[11px] text-black/35">{dateLabel(h.changedAt)} · {h.changedByName}</p></div>)}</div>}</section></div>
 </div></div></div>}
 </>}
